### ISSUE TITLE
FIT files missing Sats, HDOP, COG

### ISSUE THREAD

**Issue by Logiqx** [Logiqx/gp3s-coros#27]
FIT files are sometimes missing the sats, HDOP and COG elements.

It is has been seen for the VERTIX and VERTIX 2, but may also affect other models.

Example FIT files are attached

VERTIX

[Sola_Windsurfing20230625165331.zip](https://github.com/Logiqx/gp3s-coros/files/14562835/Sola_Windsurfing20230625165331.zip)
[Windsurfing20230711140901-spikefit.zip](https://github.com/Logiqx/gp3s-coros/files/14562844/Windsurfing20230711140901-spikefit.zip)

VERTIX 2
[Datça_Windsurfing20230629134700.zip](https://github.com/Logiqx/gp3s-coros/files/14562852/Datca_Windsurfing20230629134700.zip)

**Comment by DarianKrey** [comment]
Hey @Logiqx, can you re-upload these files? I'm getting a 404 error message.
<img width="662" alt="image" src="https://github.com/Logiqx/gp3s-coros/assets/163206742/0aa0aee5-49d1-4ad9-b7ad-4ffb5e1e2eba">

**Comment by Logiqx** [comment]
@COROS-Darian Strange. They seem to download ok to my laptop.

Here is a ZIP file containing the 3 tracks.

[coros-fit.zip](https://github.com/Logiqx/gp3s-coros/files/14591831/coros-fit.zip)

**Comment by Logiqx** [comment]
No feedback from COROS, but I have realised that these are windsurfing activities and not speedsurfing.
